Vagrant.configure(2) do |config|
  config.vm.box = "fedora/23-cloud-base"
  config.vm.provision "shell", path: 'atomicapp_tests_config.sh'

  # Setup a DHCP based private network
  config.vm.network "private_network", type: "dhcp"

  config.vm.provider "libvirt" do |libvirt, override|
    libvirt.driver = "kvm"
    libvirt.memory = 4096
    libvirt.cpus = 2
  end
end
